### ISSUE TITLE
ValueError: too many values to unpack (expected 2) How to solve?

### ISSUE THREAD

**Issue by shnulailai** [MC-E/ReVideo#5]
Great project! Could you help me with how to solve this issue? I haven't been able to get it working yet.

this error:
@SVD Inference: 2024-08-05-14-45-25
Traceback (most recent call last):
  File "/mnt/workspace/lailai/dthz/ReVideo/main/inference/sample_constant_motion.py", line 309, in <module>
    sample(input_path=args.input, path_ref=args.path_ref, ckpt=args.ckpt, config=args.config, num_frames=args.frames, num_steps=args.ddim_steps, \
  File "/mnt/workspace/lailai/dthz/ReVideo/main/inference/sample_constant_motion.py", line 64, in sample
    cotracker = torch.hub.load(co_tracker, "cotracker2").to(device)  # facebookresearch/co-tracker
  File "/mnt/workspace/lailai/env/anaconda/envs/revideo/lib/python3.10/site-packages/torch/hub.py", line 560, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/mnt/workspace/lailai/env/anaconda/envs/revideo/lib/python3.10/site-packages/torch/hub.py", line 202, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "/mnt/workspace/lailai/env/anaconda/envs/revideo/lib/python3.10/site-packages/torch/hub.py", line 135, in _parse_repo_info
    repo_owner, repo_name = repo_info.split('/')
ValueError: too many values to unpack (expected 2)

**Comment by MC-E** [comment]
You use a wrong method to load CoTracker

cotracker = torch.hub.load("facebookresearch/co-tracker", "cotracker2").to(device)

**Comment by shnulailai** [comment]
您的来信我已经收到了！
